options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/housing-predict-api:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/housing-predict-api:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Rendering templated K8s YAML file
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      sed -s '$a---' k8s/*.yaml > config.yaml.tpl &&
      sed "s/DOCKER_TAG/${SHORT_SHA}/g" config.yaml.tpl > config.yaml>
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy to K8s
  args:
  - 'apply'
  - '--namespace'
  - 'api-purchase'
  - '-f'
  - 'config.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=housing-predict-api'
images:
- gcr.io/$PROJECT_ID/purchase-predict-api:$SHORT_SHA