options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/housing-predict-api:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/housing-predict-api:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Rendering templated K8s YAML file
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      # Combine all YAML files and append '---' to the end of each file
      sed -s -e '$a\---' k8s/*.yaml > config.yaml.tpl
      # Replace DOCKER_TAG with the SHORT_SHA value
      sed "s/DOCKER_TAG/${SHORT_SHA}/g" config.yaml.tpl > config.yaml
      cat config.yaml  # Print the final config for debugging
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy to K8s
  args:
  - 'apply'
  - '--namespace'
  - 'api-purchase'
  - '-f'
  - 'config.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=housing-predict-api'
